GET http://localhost:8000/user-service/users/services
Content-Type: application/json

{

}

###
GET http://localhost:8000/user-service/users/test
Content-Type: application/json

{

}

###
POST http://localhost:8000/user-service/users/join
Content-Type: application/json

{
  "loginId": "test1",
  "loginPw" : "1234",
  "userName" : "Daehong",
  "nickName" : "닉네임1",
  "phone" : "010-1111-2222",
  "sex" : "False",
  "age" : 28,
  "role" : "ROLE_CUSTOMER"
}

###
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
"loginId" : "test1",
"loginPw" : "1234"
}
