GET http://localhost:8000/user-service/users/services
Content-Type: application/json

{

}

###
GET http://localhost:8000/user-service/users/test
Content-Type: application/json

{

}

###
POST http://localhost:8000/user-service/users/join
Content-Type: application/json

{
  "loginId" : "user1",
  "loginPw" : "1234"
}

###
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
"loginId" : "user1",
"loginPw" : "1234"
}
